-- Monthly milk subscriptions, and rider-collected cash awaiting admin approval.

-- A subscription repeats the same basket every day. Nothing is charged up front;
-- each day's delivery debits the wallet for that day only, so a customer can top
-- up whenever and the plan simply resumes.
CREATE TABLE IF NOT EXISTS subscriptions (
  id           SERIAL PRIMARY KEY,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  items        JSONB NOT NULL DEFAULT '[]',          -- [{ id, quantity }]
  labels       JSONB NOT NULL DEFAULT '[]',          -- ["2 × Farm Fresh Milk"]
  daily_total  NUMERIC(10,2) NOT NULL,
  item_count   INTEGER NOT NULL DEFAULT 0,
  address      TEXT NOT NULL,
  slot         TEXT NOT NULL,
  -- active: delivering daily. paused: customer paused it. insufficient: wallet
  -- could not cover a day, resumes by itself once the balance is topped up.
  -- cancelled: finished, kept for history.
  status       TEXT NOT NULL DEFAULT 'active',
  -- The date a delivery was last generated. The daily run only ever acts on
  -- subscriptions whose last_run_on is before today, so a run that fires twice
  -- in one day cannot bill twice.
  last_run_on  DATE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  cancelled_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON subscriptions(user_id, status);
-- The daily runner scans on this pair, and it is what makes double-billing hard.
CREATE INDEX IF NOT EXISTS idx_subscriptions_due ON subscriptions(status, last_run_on);

-- Cash handed to a rider at the door. It is a claim until an admin approves it —
-- the customer's wallet is untouched until then.
CREATE TABLE IF NOT EXISTS cash_collections (
  id              SERIAL PRIMARY KEY,
  customer_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rider_id        INTEGER REFERENCES users(id) ON DELETE SET NULL,
  rider_name      TEXT,
  amount          NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  note            TEXT,
  status          TEXT NOT NULL DEFAULT 'pending',   -- pending|approved|rejected
  -- Set once, when approved, to the wallet transaction that was created. Its
  -- presence is the guard that a claim can never be credited twice.
  transaction_id  INTEGER REFERENCES transactions(id) ON DELETE SET NULL,
  decided_at      TIMESTAMPTZ,
  decided_by      INTEGER,
  decided_by_email TEXT,
  decision_note   TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_cash_pending ON cash_collections(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cash_customer ON cash_collections(customer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cash_rider ON cash_collections(rider_id, created_at DESC);

-- A rider double-tapping "Record payment" must not create two claims. The app
-- sends a key per submission; retries of the same submission collapse into one.
ALTER TABLE cash_collections ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_cash_idempotency
  ON cash_collections(rider_id, idempotency_key) WHERE idempotency_key IS NOT NULL;

-- Orders generated by a subscription are marked so they can be told apart from
-- one-off orders in the app and the admin panel.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS subscription_id INTEGER REFERENCES subscriptions(id) ON DELETE SET NULL;
